### ISSUE TITLE
What happened to your project?

### ISSUE THREAD

**Issue by josefredohd** [Fan7asy/OgarFeeder#1]

**Comment by Fan7asy** [comment]
Still ongoing don't worry 🙂

**Comment by Fan7asy** [comment]
I'm just making a few things

**Comment by Fan7asy** [comment]
Should be done soon

**Comment by SAV-404** [comment]
I'm so exited!!!!!!!!

**Comment by Fan7asy** [comment]
I have created a multi-user system and a few other things, I am currently working on a pellet mode/AI.

**Comment by josefredohd** [comment]
@Fan7asy Thank you very much, I've been waiting for this for a week now xD
